### ISSUE TITLE
A little suggestion

### ISSUE THREAD

**Issue by saowang** [maltfield/rtd-github-pages#1]
Have read your article and your action, it can be described as cumbersome

To put it bluntly, I am here to recommend the same jekyll theme

quick start: https://github.com/rundocs/starter-slim
preview: https://rundocs.github.io/starter-slim

Thanks!

**Comment by maltfield** [comment]
If you read the guide you'll see that the motivation was largely driven to choose sphinx because reST is so powerful. I can write my own extensions in python that do complex things like pulling spreadsheets (even google docs spreadsheets via the API) with formulas (dynamic calculations) into tables at build time.

afaik, I don't think that sort of power is possible with jekyll.
